version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    container_name: analyzer-app
    volumes:
      - ./:/var/www
    networks:
      - analyzer-network
    depends_on:
      db:
        condition: service_started

  nginx:
    image: nginx:alpine
    container_name: analyzer-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - analyzer-network
  db:
    image: mysql:8.0
    container_name: analyzer-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./docker/db-data:/var/lib/mysql
    networks:
      - analyzer-network
   # healthcheck:
    #  test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
     # retries: 5
      #timeout: 10s
  redis:
    image: redis:latest
    container_name: analyzer-redis
    networks:
      - analyzer-network
  worker:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    container_name: analyzer-worker
    command: php artisan queue:work --tries=3
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - analyzer-network
    depends_on:
      app:
        condition: service_started
      redis:
        condition: service_started
      db: # ДОБАВЬ УСЛОВИЕ ДЛЯ DB
        condition: service_started
networks:
  analyzer-network:
    driver: bridge
